=== TheRealRogueByte/SeWebHW1/src/main/webapp/WEB-INF/data/recipes.dtd
<!ELEMENT recipes (recipe+)>
<!ELEMENT recipe (title, cuisineTypes, difficultyLevel)>
<!ATTLIST recipe id CDATA #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT cuisineTypes (cuisineType, cuisineType)>
<!ELEMENT cuisineType (#PCDATA)>
<!ELEMENT difficultyLevel (#PCDATA)>

=== TheRealRogueByte/SeWebHW1/target/recipe-recommender/WEB-INF/data/recipes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recipes SYSTEM "recipes.dtd">
<recipes>
    <recipe id="1">
        <title>Spaghetti Carbonara</title>
        <cuisineTypes>
            <cuisineType>Italian</cuisineType>
            <cuisineType>Mediterranean</cuisineType>
        </cuisineTypes>
        <difficultyLevel>Intermediate</difficultyLevel>
    </recipe>
    <recipe id="2">
        <title>Chicken Tikka Masala</title>
        <cuisineTypes>
            <cuisineType>Indian</cuisineType>
            <cuisineType>Asian</cuisineType>
        </cuisineTypes>
        <difficultyLevel>Intermediate</difficultyLevel>
    </recipe>
    <recipe id="3">
        <title>Tacos al Pastor</title>
        <cuisineTypes>
            <cuisineType>Mexican</cuisineType>
            <cuisineType>American</cuisineType>
        </cuisineTypes>
        <difficultyLevel>Beginner</difficultyLevel>
    </recipe>
    <recipe id="4">
        <title>Beef Bourguignon</title>
        <cuisineTypes>
            <cuisineType>French</cuisineType>
            <cuisineType>European</cuisineType>
        </cuisineTypes>
        <difficultyLevel>Advanced</difficultyLevel>
    </recipe>
    <recipe id="5">
        <title>Sushi Rolls</title>
        <cuisineTypes>
            <cuisineType>Japanese</cuisineType>
            <cuisineType>Asian</cuisineType>
        </cuisineTypes>
        <difficultyLevel>Advanced</difficultyLevel>
    </recipe>
    <recipe id="6">
        <title>Caesar Salad</title>
        <cuisineTypes>
            <cuisineType>American</cuisineType>
            <cuisineType>Western</cuisineType>
        </cuisineTypes>
        <difficultyLevel>Beginner</difficultyLevel>
    </recipe>
    <recipe id="7">
        <title>Pad Thai</title>
        <cuisineTypes>
            <cuisineType>Thai</cuisineType>
            <cuisineType>Asian</cuisineType>
        </cuisineTypes>
        <difficultyLevel>Intermediate</difficultyLevel>
    </recipe>
    <recipe id="8">
        <title>Margherita Pizza</title>
        <cuisineTypes>
            <cuisineType>Italian</cuisineType>
            <cuisineType>Mediterranean</cuisineType>
        </cuisineTypes>
        <difficultyLevel>Beginner</difficultyLevel>
    </recipe>
    <recipe id="9">
        <title>Greek Moussaka</title>
        <cuisineTypes>
            <cuisineType>Greek</cuisineType>
            <cuisineType>Mediterranean</cuisineType>
        </cuisineTypes>
        <difficultyLevel>Advanced</difficultyLevel>
    </recipe>
    <recipe id="10">
        <title>Kung Pao Chicken</title>
        <cuisineTypes>
            <cuisineType>Chinese</cuisineType>
            <cuisineType>Asian</cuisineType>
        </cuisineTypes>
        <difficultyLevel>Intermediate</difficultyLevel>
    </recipe>
    <recipe id="11">
        <title>Fish and Chips</title>
        <cuisineTypes>
            <cuisineType>British</cuisineType>
            <cuisineType>Western</cuisineType>
        </cuisineTypes>
        <difficultyLevel>Beginner</difficultyLevel>
    </recipe>
    <recipe id="12">
        <title>Tonkotsu Ramen</title>
        <cuisineTypes>
            <cuisineType>Japanese</cuisineType>
            <cuisineType>Asian</cuisineType>
        </cuisineTypes>
        <difficultyLevel>Advanced</difficultyLevel>
    </recipe>
    <recipe id="13">
        <title>Guacamole</title>
        <cuisineTypes>
            <cuisineType>Mexican</cuisineType>
            <cuisineType>American</cuisineType>
        </cuisineTypes>
        <difficultyLevel>Beginner</difficultyLevel>
    </recipe>
    <recipe id="14">
        <title>Coq au Vin</title>
        <cuisineTypes>
            <cuisineType>French</cuisineType>
            <cuisineType>European</cuisineType>
        </cuisineTypes>
        <difficultyLevel>Advanced</difficultyLevel>
    </recipe>
    <recipe id="15">
        <title>Shakshuka</title>
        <cuisineTypes>
            <cuisineType>Mediterranean</cuisineType>
            <cuisineType>Middle Eastern</cuisineType>
        </cuisineTypes>
        <difficultyLevel>Beginner</difficultyLevel>
    </recipe>
    <recipe id="16">
        <title>Butter Chicken</title>
        <cuisineTypes>
            <cuisineType>Indian</cuisineType>
            <cuisineType>Asian</cuisineType>
        </cuisineTypes>
        <difficultyLevel>Intermediate</difficultyLevel>
    </recipe>
    <recipe id="17">
        <title>Lasagna</title>
        <cuisineTypes>
            <cuisineType>Italian</cuisineType>
            <cuisineType>Mediterranean</cuisineType>
        </cuisineTypes>
        <difficultyLevel>Intermediate</difficultyLevel>
    </recipe>
    <recipe id="18">
        <title>Tom Yum Soup</title>
        <cuisineTypes>
            <cuisineType>Thai</cuisineType>
            <cuisineType>Asian</cuisineType>
        </cuisineTypes>
        <difficultyLevel>Intermediate</difficultyLevel>
    </recipe>
    <recipe id="19">
        <title>Chicken Enchiladas</title>
        <cuisineTypes>
            <cuisineType>Mexican</cuisineType>
            <cuisineType>American</cuisineType>
        </cuisineTypes>
        <difficultyLevel>Intermediate</difficultyLevel>
    </recipe>
    <recipe id="20">
        <title>Mushroom Risotto</title>
        <cuisineTypes>
            <cuisineType>Italian</cuisineType>
            <cuisineType>Mediterranean</cuisineType>
        </cuisineTypes>
        <difficultyLevel>Advanced</difficultyLevel>
    </recipe>
    <recipe id="21">
        <title>Hummus with Pita</title>
        <cuisineTypes>
            <cuisineType>Mediterranean</cuisineType>
            <cuisineType>Middle Eastern</cuisineType>
        </cuisineTypes>
        <difficultyLevel>Beginner</difficultyLevel>
    </recipe>
    <recipe id="22">
        <title>Chicken Biryani</title>
        <cuisineTypes>
            <cuisineType>Indian</cuisineType>
            <cuisineType>Asian</cuisineType>
        </cuisineTypes>
        <difficultyLevel>Advanced</difficultyLevel>
    </recipe>
    <recipe id="23">
        <title>Seafood Paella</title>
        <cuisineTypes>
            <cuisineType>Spanish</cuisineType>
            <cuisineType>Mediterranean</cuisineType>
        </cuisineTypes>
        <difficultyLevel>Advanced</difficultyLevel>
    </recipe>
    <recipe id="24">
        <title>Classic Cheeseburger</title>
        <cuisineTypes>
            <cuisineType>American</cuisineType>
            <cuisineType>Western</cuisineType>
        </cuisineTypes>
        <difficultyLevel>Beginner</difficultyLevel>
    </recipe>
</recipes>
